apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-cd-backend
spec:
  pipelineRef:
    name: pipeline-cd-backend
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-pvc