apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-cd-frontend
spec:
  pipelineRef:
    name: pipeline-cd-frontend
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-pvc